version: "3.9"

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile

    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      BROKER_URL: host.docker.internal
      TCP_SERVER_PORT: "9000"
      SECRET: "secret"
